# Generated by Django 5.1 on 2024-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
