# Generated by Django 5.1 on 2024-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
